### ISSUE TITLE
Typo in downlink, AuS L3-edge 

### ISSUE THREAD

**Issue by juejing-liu** [NSLS-II-BMM/bmm-standards#1]
Hi Bruce,

I noticed a typo for the download link of AuS, Au L3-edge, the  

Not working link (resulting in 404):
[](https://nsls-ii-bmm.github.io/bmm-standards/Data/Au/Au-L3-GoldSufide.xdi)

Working link (from GitHub project page):

[](https://github.com/NSLS-II-BMM/bmm-standards/blob/main/Data/Au/Au-L3-GoldSulfide.xdi)

The not-working link typo AuS as GoldSufide, which may be GoldSulfide.

Best,

Juejing

**Comment by bruceravel** [comment]
Wow!  Good catch!  Thanks.

Turns out it was a typo in the json file which organizes all the data.  It now seems to be fixed.
